# 日本語設定ファイル
# OneChunkGuard

# 保護ブロック種類の設定（複数定義可能）
protection-blocks:
  # デフォルトの保護ブロック
  default:
    material: END_STONE
    display-name: "&6&l保護ブロック"
    lore:
      - "&7このブロックを設置すると"
      - "&7チャンクが保護されます"
      - "&c1人1チャンクまで！"
      - ""
      - "&e設置したブロック右クリックで共同プレイヤーを設定"
      - "&e/unprotect &7- 保護を解除してブロック回収"
    parent-region: ""  # 空文字の場合は制限なし
    chunk-range: 1     # 保護するチャンクの範囲（1=1x1チャンク）
  
  # VIPプレイヤー用の保護ブロック（例）
  vip:
    material: DIAMOND_BLOCK
    display-name: "&b&lVIP保護ブロック"
    lore:
      - "&7このブロックを設置すると"
      - "&79チャンクが保護されます"
      - "&c1人1種類につき1個まで！"
      - ""
      - "&e設置したブロック右クリックで共同プレイヤーを設定"
      - "&e/unprotect vip &7- VIP保護を解除してブロック回収"
    parent-region: "vip_area"
    chunk-range: 3     # 保護するチャンクの範囲（3=3x3チャンク）
    area-name: "VIPエリア"  # エラーメッセージで表示される名前

# 保護設定
protection:
  # 保護する高さの範囲
  min-y: -64
  max-y: 320
  # 共同プレイヤーの最大数
  max-trusted-players: 5
  # アクションバーにチャンク所有者を表示するか
  show-owner-actionbar: true