name: OneChunkGuard
version: '${project.version}'
main: com.kamesuta.onechunkguard.OneChunkGuard
api-version: '1.20'
depend: [WorldGuard, WorldEdit]
description: Simple one-chunk protection plugin
authors: [ Kamesuta ]

permissions:
  onechunkguard.admin:
    description: Administrator permission (can destroy other players' protection blocks and heads)
    default: op

commands:
  unprotect:
    description: Remove chunk protection and return protection block
    usage: /<command> [type]
  trust:
    description: Add player to protected chunk
    usage: /<command> <player_name>
  untrust:
    description: Remove player from protected chunk
    usage: /<command> <player_name>
  trustlist:
    description: List all trusted players in chunk
    usage: /<command>
  giveprotectionblock:
    description: "Admin: Give specified protection blocks"
    aliases: [gpb]
    usage: /<command> <player_name> <type> [amount]
    permission: onechunkguard.admin
